### ISSUE TITLE
React.createClass()

### ISSUE THREAD

**Issue by lauterry** [Sfeir/react-movie-200#1]
Dans step-1-solution, on devrait utiliser React.createClass() pour créer un composant React. On le montre dans nos slides. Il ne faudra pas montrer une solution différente.

D'ailleurs, je ne savais pas que l'on pouvait mettre qu'une fonction. Où as tu vu ce code ? Est-ce ici  ? https://facebook.github.io/react/blog/2015/12/18/react-components-elements-and-instances.html

Si oui, on ne devrait pas aborder cette distinction dans le code du tp alors que l'on ne l'a pas aborder dans les slides

**Comment by ThomasCrevoisier** [comment]
Fixé (cf commits "Utilisation de React.createClass au lieu de dumb components")
