### ISSUE TITLE
Figer la version de React dans package.json

### ISSUE THREAD

**Issue by lauterry** [Sfeir/react-movie-200#3]
A l'étape step-3-solution, j'ai un message d'erreur suivant :  

```
npm ERR! peerinvalid The package react@0.14.3 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-dom@0.14.3 wants react@^0.14.3
npm ERR! peerinvalid Peer react-addons-test-utils@0.14.5 wants react@^0.14.5
```

Il faudrait figer la version des lib utilisé pour éviter ce genre de message.

Exemple : 

```
"react": "0.14.3",
"react-dom": "0.14.3"
```

au lieu de 

```
"react": "^0.14.3",
"react-dom": "^0.14.1",
```

**Comment by ThomasCrevoisier** [comment]
J'ai essayé de refaire une installation des modules npm et je n'arrive pas à reproduire le problème.
Est-ce que tu peux me donner la version de npm que tu utilises ?
En regardant le message d'erreur que tu donnes, figer la version de React à 0.14.3 n'est pas la solution => react-addons-test-utils requiert react@^0.14.5.
Normalement, si tu installes la dernière version de react, elle vérifie toutes contraintes de peer deps.
