### ISSUE TITLE
Insérer le markup du bouton supprimer au step-4

### ISSUE THREAD

**Issue by lauterry** [Sfeir/react-movie-200#7]
Pour gagner du temps, insérer le markup du bouton supprimer dès le step-4 pour éviter au candidat de perdre du temps à le faire.

Pensez à modifier l'énoncer de l'exo.

Penser à reprendre le markup du bouton utiliser dans angular-movie (bouton rouge avec une corbeille) et à le répercuter sur les steps suivants

```
<button class="btn btn-danger" ><i class="icon-trash icon-white"></i></button>
```

**Comment by ThomasCrevoisier** [comment]
Fixé sur les steps >= step-4-solution. Je te laisse clore l'issue. Si jamais il y a encore des problèmes sur certains steps, enlève les labels de ceux pour lesquels le problème ne se pose plus.

**Comment by lauterry** [comment]
:+1:
